"""
run_pipeline.py — Full End-to-End Pipeline Orchestrator
=========================================================
Duty-Cycle-Based Predictive Maintenance System for Heavy Mining Vehicles

IMPORTANT: All data generated and stored is SYNTHETIC.

Executes the complete pipeline in order:
  1. Load raw data (from data/raw/)
  2. Preprocessing (clean + quality log)
  3. Feature engineering (6 sub-scores)
  4. DCSS model (duty cycle severity score + risk level)
  5. Maintenance engine (interval + urgency + reason)
  6. Baseline model (fixed 30-day interval)
  7. Failure simulation (prototype + baseline, both seeded)
  8. SQLite database population (all 5 tables)
  9. Evaluation metrics computation (stored in DB)
  10. Summary report to console

Each step is timed and logged. The pipeline is idempotent — re-running
overwrites the database with fresh results (INSERT OR REPLACE).

Usage:
    python src/run_pipeline.py              # full pipeline
    python src/run_pipeline.py --from-step 5  # resume from step N (skips earlier steps)

Expected total runtime: < 60 seconds on a 4-core laptop (NFR-01).
"""

from __future__ import annotations

import sys
import time
import logging
import argparse
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import config as cfg
import database as db
from preprocessing import run_preprocessing
from feature_engineering import run_feature_engineering
from duty_cycle_model import run_duty_cycle_model
from maintenance_engine import run_maintenance_engine, apply_recommendations
from baseline import apply_baseline
from failure_simulator import simulate_breakdowns, build_initial_service_state

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("run_pipeline")

# ---------------------------------------------------------------------------
# Timing helper
# ---------------------------------------------------------------------------

class _Timer:
    def __init__(self, name: str):
        self.name = name
        self._start = 0.0

    def __enter__(self):
        self._start = time.perf_counter()
        logger.info("[STEP] %s ...", self.name)
        return self

    def __exit__(self, *args):
        elapsed = time.perf_counter() - self._start
        logger.info("[DONE] %s (%.2f s)", self.name, elapsed)
        self.elapsed = elapsed


# ---------------------------------------------------------------------------
# Step functions
# ---------------------------------------------------------------------------

def step1_load_raw(project_root: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Load raw CSVs (generated by data_generator.py)."""
    vehicles_path = project_root / cfg.VEHICLES_META_FILE
    ops_path      = project_root / cfg.OPERATIONAL_DATA_RAW_FILE
    if not vehicles_path.exists() or not ops_path.exists():
        raise FileNotFoundError(
            "Raw data files missing. Run: python src/data_generator.py"
        )
    vehicles_df = pd.read_csv(vehicles_path)
    ops_df_raw  = pd.read_csv(ops_path)
    logger.info("Raw data: %d vehicles, %d operational records.", len(vehicles_df), len(ops_df_raw))
    return vehicles_df, ops_df_raw


def step2_preprocessing(project_root: Path) -> pd.DataFrame:
    """Run preprocessing pipeline."""
    return run_preprocessing(project_root=project_root)


def step3_feature_engineering(clean_df: pd.DataFrame, project_root: Path) -> pd.DataFrame:
    """Run feature engineering on clean data."""
    return run_feature_engineering(clean_df=clean_df, project_root=project_root)


def step4_dcss_model(features_df: pd.DataFrame) -> pd.DataFrame:
    """Compute DCSS and risk classification."""
    return run_duty_cycle_model(features_df=features_df)


def step5_maintenance_engine(dcss_df: pd.DataFrame, project_root: Path) -> pd.DataFrame:
    """Apply maintenance interval recommendations."""
    return run_maintenance_engine(dcss_df=dcss_df, project_root=project_root)


def step6_baseline(features_df: pd.DataFrame) -> pd.DataFrame:
    """Apply fixed-calendar baseline model."""
    return apply_baseline(features_df)


def step7_failure_simulation(
    recs_df: pd.DataFrame,
    baseline_df: pd.DataFrame,
    clean_df: pd.DataFrame,
    vehicles_df: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Simulate breakdowns for both prototype and baseline models.
    Both use the same seeded RNG for a fair comparison.
    """
    svc_state = build_initial_service_state(clean_df, vehicles_df)

    proto_sim = simulate_breakdowns(
        recs_df, svc_state,
        interval_col="recommended_interval_days",
        model_label="prototype",
        rng=np.random.default_rng(cfg.RANDOM_SEED),
    )
    baseline_sim = simulate_breakdowns(
        baseline_df, svc_state,
        interval_col="baseline_interval_days",
        model_label="baseline",
        rng=np.random.default_rng(cfg.RANDOM_SEED),
    )
    return proto_sim, baseline_sim


def step8_populate_database(
    vehicles_df: pd.DataFrame,
    clean_df: pd.DataFrame,
    recs_df: pd.DataFrame,
    project_root: Path,
) -> None:
    """
    Create schema and populate all 5 database tables.
    Idempotent — safe to re-run.
    """
    # Schema
    db.create_schema(project_root)

    # 1. vehicles
    db.upsert_vehicles(vehicles_df, project_root)

    # 2. operational_data (cleaned records only — no duplicates)
    db.insert_operational_data(clean_df, project_root, replace=True)

    # 3. maintenance_plans (prototype recommendations)
    db.insert_maintenance_plans(recs_df, project_root)

    # 4. service_history (simulated from recommendations)
    db.insert_service_history_from_ops(recs_df, project_root, triggered_by="DCSS_MODEL")

    # 5. override_history starts empty (populated via Streamlit UI)
    logger.info("override_history: starts empty — populated via dispatcher UI.")


def step9_compute_evaluation(
    proto_sim: pd.DataFrame,
    baseline_sim: pd.DataFrame,
) -> dict:
    """
    Compute evaluation metrics and return as a dict.
    Full evaluation is in Phase 6; this computes the core metrics for DB storage.

    Metrics:
      - prototype_breakdowns    : total simulated breakdowns under prototype
      - baseline_breakdowns     : total simulated breakdowns under baseline
      - breakdowns_avoided      : baseline - prototype
      - reduction_pct           : % reduction
      - prototype_prevented     : breakdowns prevented by prototype servicing
      - baseline_prevented      : breakdowns prevented by baseline servicing
      - normal_bd_proto         : prototype breakdowns during NORMAL scenario
      - disruption_bd_proto     : prototype breakdowns during DISRUPTION scenario
      - normal_bd_base          : baseline breakdowns during NORMAL scenario
      - disruption_bd_base      : baseline breakdowns during DISRUPTION scenario
    """
    proto_bd  = int(proto_sim["sim_breakdown"].sum())
    base_bd   = int(baseline_sim["sim_breakdown"].sum())
    avoided   = base_bd - proto_bd
    reduction = round(100 * avoided / base_bd, 2) if base_bd > 0 else 0.0

    proto_prev = int(proto_sim["sim_breakdown_prevented"].sum())
    base_prev  = int(baseline_sim["sim_breakdown_prevented"].sum())

    # Scenario breakdown
    def _scenario_bd(df: pd.DataFrame, tag: str) -> int:
        return int(df[df.get("scenario_tag", df.get("scenario_tag_x", pd.Series(["NORMAL"]*len(df)))) == tag]["sim_breakdown"].sum())

    # safely get scenario_tag from either original or merged df
    def _scene_bd(df, tag):
        if "scenario_tag" in df.columns:
            return int(df[df["scenario_tag"] == tag]["sim_breakdown"].sum())
        return 0

    metrics = {
        "prototype_breakdowns":   proto_bd,
        "baseline_breakdowns":    base_bd,
        "breakdowns_avoided":     avoided,
        "reduction_pct":          reduction,
        "prototype_prevented":    proto_prev,
        "baseline_prevented":     base_prev,
        "normal_bd_proto":        _scene_bd(proto_sim, "NORMAL"),
        "disruption_bd_proto":    _scene_bd(proto_sim, "DISRUPTION"),
        "normal_bd_base":         _scene_bd(baseline_sim, "NORMAL"),
        "disruption_bd_base":     _scene_bd(baseline_sim, "DISRUPTION"),
        "target_reduction_pct":   cfg.BREAKDOWN_REDUCTION_TARGET_PCT,
        "target_met":             reduction >= cfg.BREAKDOWN_REDUCTION_TARGET_PCT,
    }
    return metrics


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run_full_pipeline(
    project_root: Path | None = None,
    from_step: int = 1,
) -> dict:
    """
    Execute the full data-to-database pipeline.

    Parameters
    ----------
    project_root : Path | None
    from_step : int
        Resume from this step (1–9). Steps before this are loaded from disk.

    Returns
    -------
    dict  evaluation metrics
    """
    if project_root is None:
        project_root = PROJECT_ROOT

    pipeline_start = time.perf_counter()
    logger.info("=" * 60)
    logger.info("PIPELINE START (from step %d)", from_step)
    logger.info("IMPORTANT: All data is SYNTHETIC.")
    logger.info("=" * 60)

    # ---- Step 1: Load raw ----
    with _Timer("Step 1: Load raw data"):
        vehicles_df, ops_df_raw = step1_load_raw(project_root)

    # ---- Step 2: Preprocessing ----
    if from_step <= 2:
        with _Timer("Step 2: Preprocessing"):
            clean_df = step2_preprocessing(project_root)
    else:
        clean_df = pd.read_csv(project_root / cfg.OPERATIONAL_DATA_CLEAN_FILE)
        logger.info("Step 2: Loaded clean data from disk (%d rows).", len(clean_df))

    # ---- Step 3: Feature engineering ----
    if from_step <= 3:
        with _Timer("Step 3: Feature engineering"):
            features_df = step3_feature_engineering(clean_df, project_root)
    else:
        features_df = pd.read_csv(project_root / cfg.OPERATIONAL_DATA_FEATURES_FILE)
        logger.info("Step 3: Loaded features from disk (%d rows).", len(features_df))

    # ---- Step 4: DCSS model ----
    with _Timer("Step 4: DCSS model"):
        dcss_df = step4_dcss_model(features_df)

    # ---- Step 5: Maintenance engine ----
    with _Timer("Step 5: Maintenance engine"):
        recs_df = step5_maintenance_engine(dcss_df, project_root)

    # ---- Step 6: Baseline ----
    with _Timer("Step 6: Baseline model"):
        baseline_df = step6_baseline(features_df)

    # ---- Step 7: Failure simulation ----
    with _Timer("Step 7: Failure simulation"):
        proto_sim, baseline_sim = step7_failure_simulation(
            recs_df, baseline_df, clean_df, vehicles_df
        )

    # ---- Step 8: Populate database ----
    with _Timer("Step 8: Populate database"):
        step8_populate_database(vehicles_df, clean_df, recs_df, project_root)

    # ---- Step 9: Evaluation metrics ----
    with _Timer("Step 9: Evaluation metrics"):
        metrics = step9_compute_evaluation(proto_sim, baseline_sim)

    total_elapsed = time.perf_counter() - pipeline_start

    # ---- Console summary ----
    print_pipeline_summary(metrics, total_elapsed)

    return metrics


# ---------------------------------------------------------------------------
# Summary printer
# ---------------------------------------------------------------------------

def print_pipeline_summary(metrics: dict, elapsed: float) -> None:
    """Print final pipeline summary to console."""
    print("\n" + "=" * 60)
    print("  PIPELINE COMPLETE — EVALUATION SUMMARY (SYNTHETIC DATA)")
    print("=" * 60)
    print(f"  Total pipeline runtime:     {elapsed:.2f} seconds")
    print()
    print(f"  Prototype breakdowns:       {metrics['prototype_breakdowns']}")
    print(f"  Baseline breakdowns:        {metrics['baseline_breakdowns']}")
    print(f"  Breakdowns avoided:         {metrics['breakdowns_avoided']}")
    print(f"  Reduction:                  {metrics['reduction_pct']:.2f}%")
    print(f"  Target ({cfg.BREAKDOWN_REDUCTION_TARGET_PCT:.0f}% reduction):      "
          f"{'MET' if metrics['target_met'] else 'NOT MET'}")
    print()
    print(f"  Prototype prevented:        {metrics['prototype_prevented']}")
    print(f"  Baseline  prevented:        {metrics['baseline_prevented']}")
    print()
    print(f"  Scenario breakdown (proto):")
    print(f"    NORMAL:      {metrics['normal_bd_proto']}")
    print(f"    DISRUPTION:  {metrics['disruption_bd_proto']}")
    print(f"  Scenario breakdown (base):")
    print(f"    NORMAL:      {metrics['normal_bd_base']}")
    print(f"    DISRUPTION:  {metrics['disruption_bd_base']}")

    # DB stats
    try:
        stats = db.get_db_stats()
        print(f"\n  Database row counts:")
        for table, count in stats.items():
            print(f"    {table:<25}: {count}")
    except Exception as e:
        print(f"\n  (Could not read DB stats: {e})")

    print("=" * 60)
    print("  NOTE: All figures above are based on SYNTHETIC data only.")
    print("  They do not represent real vehicle performance or failure rates.")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run the full mining maintenance pipeline."
    )
    parser.add_argument(
        "--from-step", type=int, default=1, choices=range(1, 10),
        help="Resume pipeline from this step (1=full run, default=1).",
    )
    args = parser.parse_args()

    metrics = run_full_pipeline(
        project_root=PROJECT_ROOT,
        from_step=args.from_step,
    )
    sys.exit(0)
