"""
data_generator.py — Synthetic Dataset Generator
================================================
Duty-Cycle-Based Predictive Maintenance System for Heavy Mining Vehicles

IMPORTANT: ALL DATA GENERATED BY THIS MODULE IS SYNTHETIC.
It is generated from statistical distributions designed to approximate realistic
mining vehicle operating conditions. It does NOT represent real sensor readings,
real vehicle behaviour, or real maintenance outcomes. It must NOT be used to make
claims about real-world system performance.

Generates:
  - data/raw/vehicles_meta.csv   : static vehicle metadata (one row per vehicle)
  - data/raw/operational_data_raw.csv : daily operational records (one row per vehicle per day)

Includes realistic correlations:
  - Higher load + route severity -> higher engine hours (compounding wear)
  - Higher fault count -> higher fault severity (fault clustering)
  - Operating stress index correlated with load + route severity
  - Recent service reduces immediate fault probability
  - Vehicle age increases base fault probability

Injects realistic data quality issues as specified in config.py:
  - Missing load values (MISSING_LOAD)
  - Invalid load values > 100 or < 0 (INVALID_LOAD)
  - Missing engine hours (MISSING_ENGINE_HOURS)
  - Duplicate records (DUPLICATE_RECORD)
  - Invalid mileage (cumulative decreases) (INVALID_MILEAGE)
  - Missing fault information (MISSING_FAULT_INFO)

Usage:
  python src/data_generator.py

Expected output:
  data/raw/vehicles_meta.csv         (40 rows)
  data/raw/operational_data_raw.csv  (~14,600 rows + injected duplicates)
  Console summary statistics
"""

from __future__ import annotations

import os
import sys
import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Path setup: allow running as script from any working directory
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import config as cfg

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("data_generator")

# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------

def _clip(value: float, low: float, high: float) -> float:
    """Clip a scalar value to [low, high]."""
    return max(low, min(high, value))


def _route_label(score: float) -> str:
    """Convert a 0–10 route severity score to a display label."""
    for label, (lo, hi) in cfg.ROUTE_SEVERITY_LABELS.items():
        if lo <= score <= hi:
            return label
    # Fallback: score == 10.0 exactly
    return "Extreme"


def _sigmoid(x: float) -> float:
    """Numerically stable sigmoid."""
    if x >= 0:
        return 1.0 / (1.0 + np.exp(-x))
    exp_x = np.exp(x)
    return exp_x / (1.0 + exp_x)


# ---------------------------------------------------------------------------
# Vehicle metadata generator
# ---------------------------------------------------------------------------

def generate_vehicles(rng: np.random.Generator) -> pd.DataFrame:
    """
    Generate static metadata for NUM_VEHICLES synthetic mining vehicles.

    Returns
    -------
    pd.DataFrame
        One row per vehicle with columns matching the `vehicles` DB table.
    """
    n = cfg.NUM_VEHICLES
    vehicle_ids = [f"VH-{i:03d}" for i in range(1, n + 1)]

    types = rng.choice(
        cfg.VEHICLE_TYPES,
        size=n,
        p=cfg.VEHICLE_TYPE_WEIGHTS,
    )

    manufacture_years = rng.integers(
        cfg.MANUFACTURE_YEAR_RANGE[0],
        cfg.MANUFACTURE_YEAR_RANGE[1] + 1,
        size=n,
    )

    sim_start_year = int(cfg.SIMULATION_START_DATE[:4])
    vehicle_age_years = sim_start_year - manufacture_years.astype(float)

    max_loads = np.array([
        rng.uniform(*cfg.MAX_LOAD_CAPACITY[vtype])
        for vtype in types
    ])

    odometers = rng.uniform(
        cfg.ODOMETER_AT_REGISTRATION_RANGE[0],
        cfg.ODOMETER_AT_REGISTRATION_RANGE[1],
        size=n,
    )

    df = pd.DataFrame({
        "vehicle_id":               vehicle_ids,
        "vehicle_type":             types,
        "manufacture_year":         manufacture_years,
        "vehicle_age_years":        vehicle_age_years.round(1),
        "max_load_capacity_tonnes": max_loads.round(1),
        "odometer_at_registration": odometers.round(1),
        "active":                   1,
    })

    logger.info("Generated metadata for %d vehicles.", n)
    return df


# ---------------------------------------------------------------------------
# Service history initialiser
# ---------------------------------------------------------------------------

def _initialise_service_state(
    vehicles_df: pd.DataFrame,
    rng: np.random.Generator,
) -> Dict[str, Dict]:
    """
    Assign each vehicle a last-service date before the simulation start.

    About 10% of vehicles will have NO prior service history (new vehicles),
    which is an edge case the system must handle gracefully.

    Returns
    -------
    dict: vehicle_id -> {"last_service_date": date | None,
                         "last_service_mileage": float | None,
                         "last_service_type": str | None,
                         "cumulative_mileage": float}
    """
    sim_start = datetime.strptime(cfg.SIMULATION_START_DATE, "%Y-%m-%d").date()
    state: Dict[str, Dict] = {}

    for _, row in vehicles_df.iterrows():
        vid = row["vehicle_id"]
        odometer = float(row["odometer_at_registration"])

        # ~10% are brand-new (edge case: no service history)
        if rng.random() < 0.10:
            state[vid] = {
                "last_service_date":    None,
                "last_service_mileage": None,
                "last_service_type":    None,
                "cumulative_mileage":   odometer,
            }
        else:
            # Last service was 1–45 days before simulation start
            days_ago = int(rng.integers(1, 46))
            last_svc_date = sim_start - timedelta(days=days_ago)
            state[vid] = {
                "last_service_date":    last_svc_date,
                "last_service_mileage": max(0.0, odometer - rng.uniform(500, 3000)),
                "last_service_type":    rng.choice(["MINOR", "MAJOR"]),
                "cumulative_mileage":   odometer,
            }

    return state


# ---------------------------------------------------------------------------
# Failure probability computation
# ---------------------------------------------------------------------------

def _failure_probability(
    fault_score_norm: float,
    route_norm: float,
    load_norm: float,
    engine_norm: float,
    mileage_norm: float,
    days_since_norm: float,
) -> float:
    """
    Compute probability of breakdown on a given day using a sigmoid function.

    All inputs are normalised to [0, 1] (sub-score / 100).

    Returns
    -------
    float in [0, 1]
    """
    logit = (
        cfg.FAILURE_ALPHA_FAULT        * fault_score_norm
        + cfg.FAILURE_ALPHA_ROUTE      * route_norm
        + cfg.FAILURE_ALPHA_LOAD       * load_norm
        + cfg.FAILURE_ALPHA_ENGINE     * engine_norm
        + cfg.FAILURE_ALPHA_MILEAGE    * mileage_norm
        + cfg.FAILURE_ALPHA_DAYS_SINCE * days_since_norm
        - cfg.FAILURE_BETA_INTERCEPT
    )
    return _sigmoid(logit)


def _sample_failure_type(rng: np.random.Generator) -> str:
    """Sample a breakdown type given the configured type probabilities."""
    types = list(cfg.FAILURE_TYPE_PROBS.keys())
    probs = list(cfg.FAILURE_TYPE_PROBS.values())
    return str(rng.choice(types, p=probs))


# ---------------------------------------------------------------------------
# Per-vehicle daily record generator
# ---------------------------------------------------------------------------

def _generate_vehicle_records(
    vehicle_id: str,
    vehicle_type: str,
    vehicle_age_years: float,
    sim_dates: List[datetime],
    svc_state: Dict,
    rng: np.random.Generator,
) -> List[Dict]:
    """
    Generate one year of daily records for a single vehicle.

    Applies realistic correlations:
    - Engine hours increase with load and route severity.
    - Fault severity correlates with fault count.
    - Operating stress index correlates with load + route severity.
    - Older vehicles have higher base fault probability.
    - Recent service lowers fault generation probability.

    Parameters
    ----------
    vehicle_id : str
    vehicle_type : str
    vehicle_age_years : float
    sim_dates : list of datetime objects (365 entries)
    svc_state : dict with current service tracking state
    rng : numpy random Generator

    Returns
    -------
    list of dicts (one per day)
    """
    records: List[Dict] = []

    last_svc_date   = svc_state["last_service_date"]
    last_svc_mileage = svc_state["last_service_mileage"]
    last_svc_type   = svc_state["last_service_type"]
    cumulative_km   = svc_state["cumulative_mileage"]

    mileage_mean, mileage_std = cfg.DAILY_MILEAGE_DIST[vehicle_type]
    engine_mean, engine_std   = cfg.ENGINE_HOURS_DIST[vehicle_type]

    for day_index, date in enumerate(sim_dates):
        date_str = date.strftime("%Y-%m-%d")

        # --- Scenario tag ---
        is_disruption = (
            cfg.DISRUPTION_START_DAY <= day_index < cfg.DISRUPTION_END_DAY
        )
        scenario_tag = "DISRUPTION" if is_disruption else "NORMAL"

        # --- Route severity (base + disruption delta) ---
        route_base = float(rng.normal(*cfg.ROUTE_SEVERITY_DIST))
        if is_disruption:
            route_base += cfg.DISRUPTION_ROUTE_SEVERITY_DELTA
        route_severity = _clip(route_base, 0.0, 10.0)
        route_label = _route_label(route_severity)

        # --- Load percentage (base + disruption delta) ---
        load_base = float(rng.normal(*cfg.LOAD_PERCENTAGE_DIST))
        if is_disruption:
            load_base += cfg.DISRUPTION_LOAD_DELTA
        load_pct = _clip(load_base, 0.0, 100.0)

        # --- Engine hours: correlated with load and route severity ---
        engine_base = float(rng.normal(engine_mean, engine_std))
        # Correlation: each point of load above 60 adds 0.05h; each route point above 5 adds 0.1h
        load_corr  = max(0.0, (load_pct - 60.0) * 0.05)
        route_corr = max(0.0, (route_severity - 5.0) * 0.1)
        engine_hours = _clip(engine_base + load_corr + route_corr, 0.0, 24.0)
        if is_disruption:
            engine_hours = _clip(engine_hours + cfg.DISRUPTION_ENGINE_HOURS_DELTA, 0.0, 24.0)

        # --- Daily mileage ---
        daily_mileage = float(rng.normal(mileage_mean, mileage_std))
        # Disruption reduces speed slightly (rough terrain)
        if is_disruption:
            daily_mileage *= 0.85
        daily_mileage = _clip(daily_mileage, 0.0, 600.0)
        prev_cumulative = cumulative_km
        cumulative_km += daily_mileage

        # --- Operating stress index: correlated with load + route ---
        stress_base = float(rng.normal(*cfg.OPERATING_STRESS_INDEX_DIST))
        stress_corr = (load_pct / 100.0) * 2.0 + (route_severity / 10.0) * 2.0
        operating_stress = _clip(stress_base + stress_corr * 0.5, 0.0, 10.0)

        # --- Days since last service ---
        if last_svc_date is not None:
            days_since = (date.date() - last_svc_date).days
        else:
            days_since = None   # new vehicle — edge case

        # --- Fault generation ---
        # Age modifier: older vehicles have higher fault rate
        age_lambda_mult = 1.0 + max(0.0, (vehicle_age_years - 4.0)) * 0.1

        # Recent service reduces fault probability
        if days_since is not None and days_since <= cfg.SERVICE_RESET_GRACE_DAYS:
            service_fault_mult = 0.3
        elif days_since is not None and days_since <= 7:
            service_fault_mult = 0.6
        else:
            service_fault_mult = 1.0

        fault_lambda_base = cfg.FAULT_COUNT_LAMBDA_NORMAL
        if is_disruption:
            fault_lambda_base *= cfg.DISRUPTION_FAULT_LAMBDA_MULTIPLIER
        fault_lambda = fault_lambda_base * age_lambda_mult * service_fault_mult
        fault_count = int(rng.poisson(fault_lambda))

        # Fault severity: correlated with count + route severity
        if fault_count > 0:
            sev_base = float(rng.normal(*cfg.FAULT_SEVERITY_DIST))
            sev_route_corr = route_severity * 0.2
            fault_severity = _clip(sev_base + sev_route_corr + (fault_count - 1) * 0.5, 0.0, 10.0)
        else:
            fault_severity = 0.0

        # --- Failure probability ---
        fault_score_raw = min(100.0,
            (fault_count * cfg.FAULT_SCORE_COUNT_WEIGHT
             + fault_severity * cfg.FAULT_SCORE_SEVERITY_WEIGHT) * 10.0
        )
        days_since_norm = min(1.0, (days_since or 30) / cfg.SERVICE_INTERVAL_DAYS)
        fail_prob = _failure_probability(
            fault_score_norm=fault_score_raw / 100.0,
            route_norm=route_severity / 10.0,
            load_norm=load_pct / 100.0,
            engine_norm=engine_hours / cfg.ENGINE_HOUR_SCORE_REF,
            mileage_norm=min(1.0, daily_mileage / cfg.MILEAGE_SCORE_REF_KM),
            days_since_norm=days_since_norm,
        )

        # --- Breakdown event (seeded random draw) ---
        breakdown_occurred = 1 if rng.random() < fail_prob else 0
        breakdown_type = _sample_failure_type(rng) if breakdown_occurred else None

        # --- Simulated maintenance trigger (simple rule for data generation) ---
        # A service is triggered if days_since >= standard interval or critical fault
        service_triggered = False
        if days_since is not None and days_since >= cfg.SERVICE_INTERVAL_DAYS:
            service_triggered = True
        elif fault_severity >= cfg.CRITICAL_FAULT_SEVERITY_THRESHOLD:
            service_triggered = True

        if service_triggered:
            last_svc_date    = date.date()
            last_svc_mileage = cumulative_km
            last_svc_type    = "MINOR" if days_since == cfg.SERVICE_INTERVAL_DAYS else "EMERGENCY"
            # After service, fault count resets
            fault_count   = 0
            fault_severity = 0.0
            breakdown_occurred = 0
            breakdown_type = None

        # --- Assemble record ---
        records.append({
            "vehicle_id":             vehicle_id,
            "date":                   date_str,
            "mileage_km":             round(daily_mileage, 2),
            "cumulative_mileage_km":  round(cumulative_km, 2),
            "engine_hours":           round(engine_hours, 2),
            "load_percentage":        round(load_pct, 2),
            "route_severity_score":   round(route_severity, 2),
            "route_severity_label":   route_label,
            "fault_count":            fault_count,
            "fault_severity_score":   round(fault_severity, 2),
            "operating_stress_index": round(operating_stress, 2),
            "days_since_last_service": days_since,
            "last_service_mileage_km": round(last_svc_mileage, 2) if last_svc_mileage else None,
            "service_type_last":      last_svc_type,
            "breakdown_occurred":     breakdown_occurred,
            "breakdown_type":         breakdown_type,
            "data_quality_flag":      None,
            "scenario_tag":           scenario_tag,
        })

    return records


# ---------------------------------------------------------------------------
# Data quality injector
# ---------------------------------------------------------------------------

def inject_data_quality_issues(
    df: pd.DataFrame,
    rng: np.random.Generator,
) -> pd.DataFrame:
    """
    Inject realistic data quality problems into the raw dataset.

    Each injection is logged in the data_quality_flag column.
    Multiple flags on the same record are comma-separated.

    Parameters
    ----------
    df : pd.DataFrame  (the clean generated records — will be modified in place)
    rng : np.random.Generator

    Returns
    -------
    pd.DataFrame with injected quality issues
    """
    n = len(df)

    def _add_flag(idx_array: np.ndarray, code: str) -> None:
        for i in idx_array:
            existing = df.at[i, "data_quality_flag"]
            df.at[i, "data_quality_flag"] = code if pd.isna(existing) else f"{existing},{code}"

    # 1. Missing load values
    missing_load_idx = rng.choice(n, size=int(n * cfg.DQ_MISSING_LOAD_RATE), replace=False)
    df.loc[missing_load_idx, "load_percentage"] = np.nan
    _add_flag(missing_load_idx, "MISSING_LOAD")

    # 2. Invalid load values (>100 or <0)
    invalid_load_idx = rng.choice(n, size=int(n * cfg.DQ_INVALID_LOAD_RATE), replace=False)
    df.loc[invalid_load_idx, "load_percentage"] = rng.choice(
        [rng.uniform(101.0, 135.0), rng.uniform(-20.0, -1.0)],
        size=len(invalid_load_idx),
    )
    _add_flag(invalid_load_idx, "INVALID_LOAD")

    # 3. Missing engine hours
    missing_eh_idx = rng.choice(n, size=int(n * cfg.DQ_MISSING_ENGINE_HOURS_RATE), replace=False)
    df.loc[missing_eh_idx, "engine_hours"] = np.nan
    _add_flag(missing_eh_idx, "MISSING_ENGINE_HOURS")

    # 4. Invalid mileage (cumulative decreases — data corruption)
    invalid_mil_idx = rng.choice(n, size=int(n * cfg.DQ_INVALID_MILEAGE_RATE), replace=False)
    for i in invalid_mil_idx:
        current_cum = df.at[i, "cumulative_mileage_km"]
        # Set cumulative lower than current — simulates odometer reset/corruption
        df.at[i, "cumulative_mileage_km"] = max(0.0, current_cum - rng.uniform(100.0, 500.0))
    _add_flag(invalid_mil_idx, "INVALID_MILEAGE")

    # 5. Missing fault information (fault_count set to NaN)
    missing_fault_idx = rng.choice(
        n, size=int(n * cfg.DQ_MISSING_FAULT_INFO_RATE), replace=False
    )
    df.loc[missing_fault_idx, "fault_count"] = np.nan
    _add_flag(missing_fault_idx, "MISSING_FAULT_INFO")

    # 6. Duplicate records
    dup_n = int(n * cfg.DQ_DUPLICATE_RATE)
    dup_source_idx = rng.choice(n, size=dup_n, replace=False)
    dup_rows = df.iloc[dup_source_idx].copy()
    _add_flag(np.array(list(dup_source_idx)), "DUPLICATE_RECORD")

    # Flag duplicates in the duplicate rows too
    for idx in dup_rows.index:
        existing = dup_rows.at[idx, "data_quality_flag"]
        dup_rows.at[idx, "data_quality_flag"] = (
            "DUPLICATE_RECORD" if pd.isna(existing) else f"{existing},DUPLICATE_RECORD"
        )

    df = pd.concat([df, dup_rows], ignore_index=True)

    total_issues = (df["data_quality_flag"].notna()).sum()
    logger.info(
        "Injected data quality issues: %d records affected (%.1f%% of dataset).",
        total_issues,
        100.0 * total_issues / len(df),
    )
    return df


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

def generate_dataset(output_dir: Path | None = None) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Generate the complete synthetic dataset.

    Parameters
    ----------
    output_dir : Path | None
        Project root directory. Defaults to PROJECT_ROOT.

    Returns
    -------
    Tuple[pd.DataFrame, pd.DataFrame]
        (vehicles_df, operational_df)
    """
    if output_dir is None:
        output_dir = PROJECT_ROOT

    rng = np.random.default_rng(cfg.RANDOM_SEED)

    # --- Simulation dates ---
    sim_start = datetime.strptime(cfg.SIMULATION_START_DATE, "%Y-%m-%d")
    sim_dates = [sim_start + timedelta(days=i) for i in range(cfg.SIMULATION_DAYS)]

    logger.info(
        "Generating synthetic dataset: %d vehicles, %d days (%s to %s).",
        cfg.NUM_VEHICLES,
        cfg.SIMULATION_DAYS,
        sim_dates[0].strftime("%Y-%m-%d"),
        sim_dates[-1].strftime("%Y-%m-%d"),
    )
    logger.info(
        "Disruption scenario: days %d to %d (index).",
        cfg.DISRUPTION_START_DAY,
        cfg.DISRUPTION_END_DAY,
    )
    logger.info("IMPORTANT: All generated data is SYNTHETIC.")

    # --- Vehicle metadata ---
    vehicles_df = generate_vehicles(rng)

    # --- Initialise service state ---
    svc_states = _initialise_service_state(vehicles_df, rng)

    # --- Generate daily records per vehicle ---
    all_records: List[Dict] = []
    for _, vrow in vehicles_df.iterrows():
        vid = vrow["vehicle_id"]
        records = _generate_vehicle_records(
            vehicle_id=vid,
            vehicle_type=str(vrow["vehicle_type"]),
            vehicle_age_years=float(vrow["vehicle_age_years"]),
            sim_dates=sim_dates,
            svc_state=svc_states[vid],
            rng=rng,
        )
        all_records.extend(records)
        logger.debug("Generated %d records for %s.", len(records), vid)

    operational_df = pd.DataFrame(all_records)
    logger.info("Generated %d raw operational records.", len(operational_df))

    # --- Inject data quality issues ---
    operational_df = inject_data_quality_issues(operational_df, rng)

    # --- Save to disk ---
    raw_dir = output_dir / cfg.RAW_DATA_DIR
    raw_dir.mkdir(parents=True, exist_ok=True)

    vehicles_path = output_dir / cfg.VEHICLES_META_FILE
    operational_path = output_dir / cfg.OPERATIONAL_DATA_RAW_FILE

    vehicles_df.to_csv(vehicles_path, index=False)
    operational_df.to_csv(operational_path, index=False)

    logger.info("Saved vehicles metadata to: %s", vehicles_path)
    logger.info("Saved operational data to:  %s", operational_path)

    return vehicles_df, operational_df


# ---------------------------------------------------------------------------
# Summary statistics printer
# ---------------------------------------------------------------------------

def print_summary(vehicles_df: pd.DataFrame, operational_df: pd.DataFrame) -> None:
    """Print a concise summary of the generated dataset to stdout."""
    n_records = len(operational_df)
    n_vehicles = len(vehicles_df)
    n_breakdowns = int(operational_df["breakdown_occurred"].sum())
    n_disruption = int((operational_df["scenario_tag"] == "DISRUPTION").sum())
    n_quality_issues = int(operational_df["data_quality_flag"].notna().sum())
    dup_count = int(
        operational_df["data_quality_flag"]
        .fillna("")
        .str.contains("DUPLICATE_RECORD")
        .sum()
    )

    print("\n" + "=" * 60)
    print("  SYNTHETIC DATASET GENERATION SUMMARY")
    print("  (All data is SYNTHETIC — not real mining data)")
    print("=" * 60)
    print(f"  Vehicles:                  {n_vehicles}")
    print(f"  Total operational records: {n_records}")
    print(f"  Normal-scenario records:   {n_records - n_disruption}")
    print(f"  Disruption-scenario records:{n_disruption}")
    print(f"  Total breakdown events:    {n_breakdowns}")
    print(f"  Breakdown rate:            {100*n_breakdowns/n_records:.2f}%")
    print(f"  Records with quality flags:{n_quality_issues} ({100*n_quality_issues/n_records:.1f}%)")
    print(f"  Injected duplicates:       {dup_count}")

    print("\n  Vehicle type distribution:")
    for vtype, count in vehicles_df["vehicle_type"].value_counts().items():
        print(f"    {vtype:<15}: {count}")

    print("\n  Breakdown type distribution (raw):")
    for btype, count in operational_df["breakdown_type"].value_counts().items():
        print(f"    {btype:<15}: {count}")

    print("\n  Scenario breakdown counts:")
    grp = operational_df.groupby("scenario_tag")["breakdown_occurred"].sum()
    for tag, cnt in grp.items():
        print(f"    {tag:<15}: {cnt} breakdowns")

    print("\n  Data quality flag counts:")
    all_flags: List[str] = []
    for flags_str in operational_df["data_quality_flag"].dropna():
        all_flags.extend(str(flags_str).split(","))
    flag_series = pd.Series(all_flags)
    for flag, count in flag_series.value_counts().items():
        print(f"    {flag:<30}: {count}")

    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    vehicles_df, operational_df = generate_dataset(output_dir=PROJECT_ROOT)
    print_summary(vehicles_df, operational_df)
    print("Phase 2 complete: Raw dataset generated successfully.")
    print(f"  -> {PROJECT_ROOT / cfg.VEHICLES_META_FILE}")
    print(f"  -> {PROJECT_ROOT / cfg.OPERATIONAL_DATA_RAW_FILE}")
